# Generated by Django 5.1.4 on 2025-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notizen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='completed',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default='Kein Inhalt'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
